### ISSUE TITLE
Stuck at 0 %

### ISSUE THREAD

**Issue by aleqcz** [eik3/loxgraph#3]
Hi,
any ideas what could be wrong, I have installed loxgraph on Loxone 8.3, but when I open <ip>/loxgraph, it displays just 0 % in the center of the screen and that's it. Same in all three major browsers...

Thanks,
Aleq

**Comment by eik3** [comment]
Can you see anything in the console/network tab when you open the developer tools in your browser before you reload the page?

**Comment by aleqcz** [comment]
Hi eik3,
thanks for quick response. This is in console in Chrome:

GET http://192.168.1.77/stats/0d745096-0090-0512-fffffae984b19f22.201706.xml 404 (Not Found)

stack:
```
send@userscript.html?id=b…cc-285ac959fc72:101
ajax@userscript.html?id=b…cc-285ac959fc72:101
Loxgraph.Stat.Stat.processQueue@script.coffee:100
Loxgraph.Stat.Stat.buildArray@script.coffee:132
(anonymous)@jquery-2.1.0.min.js:2
j@jquery-2.1.0.min.js:2
fireWith@jquery-2.1.0.min.js:2
(anonymous)@jquery-2.1.0.min.js:2
j@jquery-2.1.0.min.js:2
fireWith@jquery-2.1.0.min.js:2
(anonymous)@jquery-2.1.0.min.js:2
j@jquery-2.1.0.min.js:2
fireWith@jquery-2.1.0.min.js:2
x@jquery-2.1.0.min.js:4
(anonymous)@jquery-2.1.0.min.js:4
XMLHttpRequest.send (async)
send@jquery-2.1.0.min.js:4
ajax@jquery-2.1.0.min.js:4
Loxgraph.Stat.Stat.loadFile@script.coffee:53
Loxgraph.Stat.Stat.go@script.coffee:137
(anonymous)@script.coffee:139
CoffeeScript.run@coffee-script.js:12
n@coffee-script.js:12
(anonymous)@coffee-script.js:12
r.onreadystatechange@coffee-script.js:12
XMLHttpRequest.send (async)
undefined.CoffeeScript.load@coffee-script.js:12
c@coffee-script.js:12
runScripts@coffee-script.js:12
```

I have searched /data/LoxAPP3.json for "0d745096-0090-0512-fffffae984b19f22" or even "0d745096-0090-0512" but haven't found it. I wonder where is it coming from...

Best regards,
Aleq

**Comment by aleqcz** [comment]
Hi,
is there anything I could help with?

Thanks,
A.

**Comment by eik3** [comment]
Sorry for missing your reply earlier.
Try to open  http://192.168.1.77/stats/, open the source and search for `0d745096-0090-0512-fffffae984b19f22.201706.xml`. There you can see the name of the stat/sensor. 
It seems to me like a bug of Loxone that it lists xml files on `/stats` that are not existent. I'd suggest you report this problem to Loxone support to find out how you can delete those entries in `/stats`. It has nothing to do with Loxgraph though, Loxgraph just relies on Loxone to give a list of all available stat files at `/stats`.

**Comment by aleqcz** [comment]
Hi Eik3,
thanks a lot. I have found the digital intput which might have had statistics turned on once, but not anymore. Something must have gon wrong, because it was listed in stats, but it was really not present (404). Turning the statistics on; save; turning it back off and save again in Loxone Config did not help, but what seems to have helped was to login to Miniserver via FTP and delete that 0d745096-0090-0512-fffffae984b19f22.201706 file (it was 0 bytes large).

Thanks!
Aleq

**Comment by eik3** [comment]
Does Loxgraph now work for you? Feel free to close this issue if it's solved.

**Comment by aleqcz** [comment]
Ah, yes - forgot to close the ticket, not familiar with it yet that much.

It works flawlessly, thank you.
