### ISSUE TITLE
Synchronize Graphs

### ISSUE THREAD

**Issue by eik3** [eik3/loxgraph#4]
The charting library [supports](http://dygraphs.com/gallery/#g/synchronize) graph sync and it would be handy to have this available in Loxgraph!

/cc @aleqcz

**Comment by aleqcz** [comment]
Thanks for the tip. I have forked your repo and have played with it. First experimental version available here: [https://github.com/aleqcz/loxgraph/tree/synchronization](url)

**Comment by eik3** [comment]
Thanks Aleš! 

I've had a look now and sync works fine in your fork. However, I noticed a small visual glitch regarding the Graph title and the rolling average field in the lower left corner of the graph:

Loxgraph master:
![original](https://user-images.githubusercontent.com/17581/37251826-727d0b0c-2517-11e8-8fe0-5e136588aee8.png)

Fork:
![fork](https://user-images.githubusercontent.com/17581/37251830-81fb4170-2517-11e8-8d0f-cff91014d29c.png)

Feel free to PR, I'm happy to merge once the issue is fixed!

**Comment by aleqcz** [comment]
Hi Eike,
fixed.
![image](https://user-images.githubusercontent.com/1750538/37256391-56cb61b8-255a-11e8-85e8-f545d1f330d1.png)
New dygraph required new CSS. I'll send Pull Request shortly.
Known issues - resizing browser window results in misplaced selected value label. After an hour of investigating I realized it's dygraph bug visible in their demos as well.

Cheers,
Aleš

**Comment by eik3** [comment]
Fixed by #5
